package com.example.app.flightproviderb.flightdetails;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T17:06:42.942+03:00
 * Generated source version: 4.1.5
 *
 */
@WebService(targetNamespace = "http://www.travelport.com/service/air_v54_0", name = "AirExchangeProcessPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AirExchangeProcessPortType {

    @WebMethod(action = "http://localhost:8080/kestrel/AirService")
    @WebResult(name = "AirExchangeRsp", targetNamespace = "http://www.travelport.com/schema/air_v54_0", partName = "result")
    public AirExchangeRsp service(

        @WebParam(partName = "parameters", name = "AirExchangeReq", targetNamespace = "http://www.travelport.com/schema/air_v54_0")
        AirExchangeReq parameters
    ) throws AirFaultMessage;
}
