
package com.example.app.flightproviderb.flightdetails;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T17:06:42.931+03:00
 * Generated source version: 4.1.5
 */

@WebFault(name = "ErrorInfo", targetNamespace = "http://www.travelport.com/schema/common_v54_0")
public class AirFaultMessage extends Exception {

    private com.example.app.flightproviderb.flightdetails.ErrorInfo faultInfo;

    public AirFaultMessage() {
        super();
    }

    public AirFaultMessage(String message) {
        super(message);
    }

    public AirFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AirFaultMessage(String message, com.example.app.flightproviderb.flightdetails.ErrorInfo errorInfo) {
        super(message);
        this.faultInfo = errorInfo;
    }

    public AirFaultMessage(String message, com.example.app.flightproviderb.flightdetails.ErrorInfo errorInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = errorInfo;
    }

    public com.example.app.flightproviderb.flightdetails.ErrorInfo getFaultInfo() {
        return this.faultInfo;
    }
}
