
package com.example.app.flightproviderb.flightdetails;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T17:06:42.817+03:00
 * Generated source version: 4.1.5
 *
 */
public final class AirRefundTicketPortType_AirRefundTicketPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.travelport.com/service/air_v54_0", "AirService");

    private AirRefundTicketPortType_AirRefundTicketPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AirService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URI(args[0]).toURL();
                }
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AirService ss = new AirService(wsdlURL, SERVICE_NAME);
        AirRefundTicketPortType port = ss.getAirRefundTicketPort();

        {
        System.out.println("Invoking service...");
        com.example.app.flightproviderb.flightdetails.AirRefundReq _service_parameters = null;
        try {
            com.example.app.flightproviderb.flightdetails.AirRefundRsp _service__return = port.service(_service_parameters);
            System.out.println("service.result=" + _service__return);

        } catch (AirFaultMessage e) {
            System.out.println("Expected exception: AirFaultMessage has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
