
package com.example.app.flightproviderb.flightdetails;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="OriginApplication" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="CIDBNumber">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             <pattern value="\d{10}"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "BillingPointOfSaleInfo", namespace = "http://www.travelport.com/schema/common_v54_0")
public class BillingPointOfSaleInfo {

    /**
     * Name of the Point of Sale application which initiated the Request.This information will be provided as part of the provisioning of the user.
     * 
     */
    @XmlAttribute(name = "OriginApplication", required = true)
    protected String originApplication;
    /**
     * A 10 Digit customer number generated by CIDB system.
     * 
     */
    @XmlAttribute(name = "CIDBNumber")
    protected BigInteger cidbNumber;

    /**
     * Name of the Point of Sale application which initiated the Request.This information will be provided as part of the provisioning of the user.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginApplication() {
        return originApplication;
    }

    /**
     * Sets the value of the originApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOriginApplication()
     */
    public void setOriginApplication(String value) {
        this.originApplication = value;
    }

    /**
     * A 10 Digit customer number generated by CIDB system.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCIDBNumber() {
        return cidbNumber;
    }

    /**
     * Sets the value of the cidbNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     * @see #getCIDBNumber()
     */
    public void setCIDBNumber(BigInteger value) {
        this.cidbNumber = value;
    }

}
