package com.example.app.flightproviderb.flightdetails;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T17:06:42.955+03:00
 * Generated source version: 4.1.5
 *
 */
@WebService(targetNamespace = "http://www.travelport.com/service/air_v54_0", name = "FlightDetailsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FlightDetailsPortType {

    @WebMethod(action = "http://localhost:8080/kestrel/FlightService")
    @WebResult(name = "FlightDetailsRsp", targetNamespace = "http://www.travelport.com/schema/air_v54_0", partName = "result")
    public FlightDetailsRsp service(

        @WebParam(partName = "parameters", name = "FlightDetailsReq", targetNamespace = "http://www.travelport.com/schema/air_v54_0")
        FlightDetailsReq parameters
    ) throws AirFaultMessage;
}
