package com.example.app.flightproviderb.flightdetails;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T17:06:42.963+03:00
 * Generated source version: 4.1.5
 *
 */
@WebServiceClient(name = "FlightService",
                  wsdlLocation = "classpath:/air_v54_0/Air.wsdl",
                  targetNamespace = "http://www.travelport.com/service/air_v54_0")
public class FlightService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.travelport.com/service/air_v54_0", "FlightService");
    public static final QName FlightDetailsPort = new QName("http://www.travelport.com/service/air_v54_0", "FlightDetailsPort");
    public static final QName FlightInfoPort = new QName("http://www.travelport.com/service/air_v54_0", "FlightInfoPort");
    static {
        URL url = FlightService.class.getClassLoader().getResource("/air_v54_0/Air.wsdl");
        if (url == null) {
            url = FlightService.class.getClassLoader().getResource("air_v54_0/Air.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(FlightService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:/air_v54_0/Air.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FlightService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FlightService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FlightService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FlightService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FlightService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FlightDetailsPortType
     */
    @WebEndpoint(name = "FlightDetailsPort")
    public FlightDetailsPortType getFlightDetailsPort() {
        return super.getPort(FlightDetailsPort, FlightDetailsPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightDetailsPortType
     */
    @WebEndpoint(name = "FlightDetailsPort")
    public FlightDetailsPortType getFlightDetailsPort(WebServiceFeature... features) {
        return super.getPort(FlightDetailsPort, FlightDetailsPortType.class, features);
    }


    /**
     *
     * @return
     *     returns FlightInfoPortType
     */
    @WebEndpoint(name = "FlightInfoPort")
    public FlightInfoPortType getFlightInfoPort() {
        return super.getPort(FlightInfoPort, FlightInfoPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightInfoPortType
     */
    @WebEndpoint(name = "FlightInfoPort")
    public FlightInfoPortType getFlightInfoPort(WebServiceFeature... features) {
        return super.getPort(FlightInfoPort, FlightInfoPortType.class, features);
    }

}
